### PR TITLE
Update copyright year & symbol

### PR DESCRIPTION
**Pull request by Xashyar**
Copyright © 2019-2020 Proton Technologies AG

### CODE REVIEW

**Comment by kaplun** [comment]
Actually I think the correct script should be `2019-2020`.

**Comment by Xashyar** [comment]
> Actually I think the correct script should be `2019-2020`.

Should the day refer to the period within which the app got published on GitHub or the launch of the app in general?

https://protonvpn.com/blog/unlimited-android-vpn/

According to this blog post it was launched in 2018.

**Comment by kaplun** [comment]
IMHO what is being copyrighted is the source code, which publicly exist only since 2019.

**Comment by Xashyar** [comment]
> Actually I think the correct script should be `2019-2020`.

@kaplun 
Done!

**Comment by AlgirdasPundzius** [comment]
@Xashyar looks good, but could you also squash the two commits into one ?

**Comment by AlgirdasPundzius** [comment]
Closing as inactive. Feel free to reopen after updating

**Pull request closed without merging**
