### PR TITLE
Add touch states

### PR DESCRIPTION
**Pull request by thgoebel**
Adds a touch state to the ProtonSwitch and to the Secure Core switches in the main screen and the profiles activity.

I would like to see touch states on the "Next" and "Skip" buttons of the onboarding and the "Got it" button of the Onboarding Dialogs as well, but those won't be one-line changes so I'll leave them for later.

You might notice that I'm a great advocate of touch states :)

### CODE REVIEW

**Comment by AlgirdasPundzius** [comment]
Could you remove touch states on secure core switches ? Because we have already refactored those places a bit, so only switch itself will change the value (unlike clicking on text like now).

**Comment by thgoebel** [comment]
Both, just the one in the home page, or just the one in the profiles screen?

**Comment by mateusz-markowicz** [comment]
We should have a bit more informative commit message here, like "Add touch state to ProtonSwitch"

**Comment by thgoebel** [comment]
> we have already refactored those places a bit, so only switch itself will change the value (unlike clicking on text like now)

Out of interest, what was the rational behind that?

To be fair, the Material Design guidelines don't specify whether the touch state should cover just the switch or the entire row AFAIK. On the other hand, when I look at AOSP, all of Google's apps, and nearly all other apps out there that make use of Material Design in some shape or form, they all have the touch area on the entire row.

Having the touch area just on the switch feels more like an iOS thing to do. So I'm really curious, why break with something us Android users have come to be accustomed to? What's the design argument behind that?

**Comment by AlgirdasPundzius** [comment]
Well, the rationale is that we have some more complex looking switches in Settings and those are not made to change on entire view (though that could be changed as well). 
So the idea was to have unified behaviour across the app. And while I personally prefer switch to change not only on switch itself, the descision we taken to change the value only on the switch itself.

**Comment by thgoebel** [comment]
Makes sense, thanks! Also in the meantime I saw that the ProtonMail app only toggles on the switch itself, too, so at least it's consistent across your products.

**Comment by AlgirdasPundzius** [comment]
Should be visible in master :)

**Pull request closed without merging**
